name: ubee_mini
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  email_validator: ^2.1.16
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  firebase_auth: ^4.14.1
  get_it: ^7.6.4
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/account_circle.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: SourceSans
      fonts:
        - asset: fonts/SourceSans3-Black.ttf
          weight: 900
        - asset: fonts/SourceSans3-ExtraBold.ttf
          weight: 800
        - asset: fonts/SourceSans3-Bold.ttf
          weight: 700
        - asset: fonts/SourceSans3-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSans3-Medium.ttf
          weight: 500
        - asset: fonts/SourceSans3-Regular.ttf
          weight: 400
        - asset: fonts/SourceSans3-Light.ttf
          weight: 300
        - asset: fonts/SourceSans3-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceSans3-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/SourceSans3-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SourceSans3-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceSans3-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SourceSans3-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SourceSans3-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/SourceSans3-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceSans3-ExtraLightItalic.ttf
          weight: 200
          style: italic
        

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
