// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtaqejEEaDRFsvkw5NG2epOx8-W85HRU',
    appId: '1:412914733828:web:6ee4638a096110d0673651',
    messagingSenderId: '412914733828',
    projectId: 'ubeemini-2ab03',
    authDomain: 'ubeemini-2ab03.firebaseapp.com',
    storageBucket: 'ubeemini-2ab03.appspot.com',
    measurementId: 'G-FQQ1BXBEMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB8k_YhxdVPourpMsCKhKsTejNOxLE0Oc',
    appId: '1:412914733828:android:4e1faabd9adbb57c673651',
    messagingSenderId: '412914733828',
    projectId: 'ubeemini-2ab03',
    storageBucket: 'ubeemini-2ab03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRGiSffK4W9cf69IVsU3ah_IpWdUxboX8',
    appId: '1:412914733828:ios:d9532f7710cb7624673651',
    messagingSenderId: '412914733828',
    projectId: 'ubeemini-2ab03',
    storageBucket: 'ubeemini-2ab03.appspot.com',
    iosBundleId: 'com.example.ubeeMini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRGiSffK4W9cf69IVsU3ah_IpWdUxboX8',
    appId: '1:412914733828:ios:6d14b4f002e4a34b673651',
    messagingSenderId: '412914733828',
    projectId: 'ubeemini-2ab03',
    storageBucket: 'ubeemini-2ab03.appspot.com',
    iosBundleId: 'com.example.ubeeMini.RunnerTests',
  );
}
